# Generated by Django 2.1.7 on 2019-03-27 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctores',
            new_name='Doctor',
        ),
    ]
