# Generated by Django 2.1.7 on 2019-03-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0006_auto_20190327_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
