# Generated by Django 2.1.7 on 2019-03-28 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctores', '0008_auto_20190327_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('amaterno', models.CharField(max_length=30)),
                ('apaterno', models.CharField(max_length=30)),
                ('image', models.ImageField(default='default.jpg', upload_to='docs_pics')),
                ('genero', models.CharField(blank=True, choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre')], max_length=16)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('numero_celular', models.CharField(max_length=10, null=True, unique=True)),
                ('cedula', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='doc',
            name='user',
        ),
        migrations.DeleteModel(
            name='Doc',
        ),
    ]
