# Generated by Django 2.1.7 on 2019-03-28 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctores', '0009_auto_20190327_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('apaterno', models.TextField(max_length=20)),
                ('image', models.ImageField(default='default.jpg', upload_to='doctores_pics')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='docs',
            name='author',
        ),
        migrations.DeleteModel(
            name='Docs',
        ),
    ]
