# Generated by Django 2.1.7 on 2019-03-27 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190326_1926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='consultorio',
        ),
        migrations.DeleteModel(
            name='doctor',
        ),
    ]
