# Generated by Django 2.1.7 on 2019-03-27 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_consultorios_doctores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consultorios',
        ),
    ]
