# Generated by Django 2.1.7 on 2019-03-27 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_delete_consultorios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctores',
        ),
    ]
