# Generated by Django 2.1.7 on 2019-04-02 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_consultorios_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=20)),
                ('fecha', models.CharField(max_length=20)),
                ('curp', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('municipio', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=20)),
                ('consultorio', models.ManyToManyField(to='user.Consultorios')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Doctors')),
                ('nombre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.perfiles')),
            ],
        ),
    ]
