# Generated by Django 2.1.7 on 2019-04-02 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20190402_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendar_citas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=20)),
                ('genero', models.CharField(blank=True, choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre')], max_length=16)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('curp', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('municipio', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=20)),
                ('Turno', models.CharField(blank=True, choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino')], max_length=16)),
                ('consultorio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Consultorios')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Doctors')),
                ('nombre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.perfiles')),
            ],
        ),
        migrations.RemoveField(
            model_name='agendar_cita',
            name='consultorio',
        ),
        migrations.RemoveField(
            model_name='agendar_cita',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='agendar_cita',
            name='nombre',
        ),
        migrations.DeleteModel(
            name='Agendar_cita',
        ),
    ]
