# Generated by Django 2.1.7 on 2019-04-02 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20190402_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendar_citas',
            name='especialidad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Especialidades'),
        ),
    ]
