# Generated by Django 2.1.7 on 2019-04-02 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0014_auto_20190402_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendar_cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=20)),
                ('curp', models.CharField(max_length=20)),
                ('genero', models.CharField(blank=True, choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre')], max_length=16)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('email', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('municipio', models.CharField(max_length=20)),
                ('Turno', models.CharField(blank=True, choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino')], max_length=16)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('consultorio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Consultorios')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Doctors')),
                ('especialidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Especialidades')),
                ('nombre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.perfiles')),
            ],
        ),
        migrations.RemoveField(
            model_name='agendar_citas',
            name='consultorio',
        ),
        migrations.RemoveField(
            model_name='agendar_citas',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='agendar_citas',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='agendar_citas',
            name='nombre',
        ),
        migrations.DeleteModel(
            name='Agendar_citas',
        ),
    ]
